#!/usr/bin/env bash
# A script that displays:
# 'To infinity and beyond' indefinitely
# 'sleep 2' in between each iteration
# 'I am invincible!!!' when receiving a 'SIGTERM' signal

trap 'echo "I am invincible!!!"' SIGTERM
while :; do
	echo "To infinity and beyond"
	sleep 2
done
