#!/usr/bin/env bash
#print "Best School" in all iterations
#except:
#Iteration 4: prints `bad luck`
#Iteration 8: prints `good luck`

count=0

while [ $count -lt 10 ]
do
if [ $count -eq 3 ]
then
	echo "bad luck"
elif [ $count -eq 7 ]
then
	echo "good luck"

else
	echo "Best School"
fi
	(( count++ ))
done
