#!/usr/bin/env bash
#displays numbers 1 - 20
#displays `4` then `bad luck from China` in 4th iteration
#displays `9` then `bad luck from Japan` in 9th iteration
#displays `17` then `bad luck from Italy` in the 17th iter

count=1

while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	(( count++ ))

done
